version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - "5000:5000"
    networks:
      - my_network
    restart: unless-stopped

  backend:
    build: 
      context: ./backend
    # container_name: fm_playground
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      DB_PORT: "5432"
      APP_SECKET_KEY: "app-secret-key"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - my_network
    restart: unless-stopped
  
  postgres:
    image: postgres:15.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge
