version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - "5000:5000"
    networks:
      - my_network
    restart: unless-stopped

  backend:
    build: 
      context: ./backend
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      APP_SECKET_KEY: ${APP_SECKET_KEY}
      FLASK_ENV: ${FLASK_ENV}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - my_network
    env_file:
      - .env
    restart: unless-stopped
  
  postgres:
    image: postgres:15.4
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    networks:
      - my_network
  
  # Development purpose only
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: soaib@soaib.com
      PGADMIN_DEFAULT_PASSWORD: pass123
    ports:
      - "5050:80"
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge
