version: '3'
services:
  frontend:
    image: ghcr.io/se-buw/fm-playground-frontend:latest
    container_name: fmp-frontend
    env_file:
      - .env
    ports:
      - "5173:5173"
    networks:
      - my_network
    restart: unless-stopped
  
  backend:
    image: ghcr.io/se-buw/fm-playground-backend:latest
    container_name: fmp-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - my_network
    restart: unless-stopped
  

networks:
  my_network:
    driver: bridge