version: '3'

services:
  # Frontend for limboole, z3, and nuxmv
  frontend:
    build: 
      context: ./frontend
    ports:
      - "5000:5000"
    networks:
      - my_network
    restart: unless-stopped
  
  # Application backend
  backend:
    build: 
      context: ./backend
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      APP_SECKET_KEY: ${APP_SECKET_KEY}
      FLASK_ENV: ${FLASK_ENV}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - my_network
    env_file:
      - .env
    restart: unless-stopped
  
  # Alloy application with meteor
  meteor:
    image: alloy-app:latest
    container_name: meteor
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - postgres
    links:
      - mongo
      - api
    env_file:
      - .env
    networks:
      - my_network
    restart: unless-stopped
  
  # Main database
  postgres:
    image: postgres:15.4
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    networks:
      - my_network
    restart: unless-stopped
  
  # Alloy api
  api:
    build:
      context: ./alloy-app/api/
    container_name: api
    ports:
      - "8080:8080"
    networks:
      - my_network
    restart: unless-stopped
  
  # Database for alloy
  mongo:
    image: mongo:latest
    container_name: mongo
    command: mongod --storageEngine=wiredTiger
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - my_network
    restart: unless-stopped

  # Development purpose only
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: soaib@soaib.com
      PGADMIN_DEFAULT_PASSWORD: pass123
    ports:
      - "5050:80"
    networks:
      - my_network

volumes:
  postgres_data:
  mongo_data:

networks:
  my_network:
    driver: bridge
