version: '3'
services:
  meteor:
    build:
      context: ./meteor/
    container_name: meteor
    ports:
      - "3010:3000"
    links:
      - mongo
      - api
    env_file:
      - .env
  mongo:
    image: mongo:latest
    container_name: mongo
    command: mongod --storageEngine=wiredTiger
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
  api:
    build:
      context: ./api/
    container_name: api
    ports:
      - "8080:8080"