name: CI for GHCR

on:
  push:
    branches:
      - 'main'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and push Backend
        run: |
          cd backend
          docker build -t ghcr.io/fm-play-backend:latest .
          echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
          docker push ghcr.io/fm-play-backend:latest
      
      - name: Build and push Frontend
        run: |
          pwd
          cd ../frontend
          docker build -t ghcr.io/fm-play-frontend:latest .
          echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
          docker push ghcr.io/fm-play-frontend:latest